name: 'Databricks CLI Runner'
description: 'Runs arbitrary Databricks CLI commands'
inputs:
  command:  # id of input
    description: 'Full command string of a valid Databricks CLI command'
    required: true
    default: 'databricks'
outputs:
  output: # id of output
  description: 'The output of the command'
branding:
  icon: "align-justify"
  color: "red"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ command }}